#pragma once
// Auto-generated by tools/generate_localization_bindings.ps1. Do not edit by hand.
#include <string>

struct LocalizationKeysAccessor
{
        const char* Get(const std::string& key) const;

        // Toggle me with %s
        inline const char* Toggle_me_with_s() const { return Get("Toggle me with %s"); }

        // Toggle Online with %s
        inline const char* Toggle_Online_with_s() const { return Get("Toggle Online with %s"); }

        // Toggle HUD with %s
        inline const char* Toggle_HUD_with_s() const { return Get("Toggle HUD with %s"); }

        // Generate Debug Logs
        inline const char* Generate_Debug_Logs() const { return Get("Generate Debug Logs"); }

        // Debug_log_details
        inline const char* Debug_log_details() const { return Get("Debug_log_details"); }

        // Online
        inline const char* Online() const { return Get("Online"); }

        // Gameplay settings
        inline const char* Gameplay_settings() const { return Get("Gameplay settings"); }

        // Custom palettes
        inline const char* Custom_palettes() const { return Get("Custom palettes"); }

        // Hitbox overlay
        inline const char* Hitbox_overlay() const { return Get("Hitbox overlay"); }

        // FrameHistory
        inline const char* FrameHistory() const { return Get("FrameHistory"); }

        // Framedata
        inline const char* Framedata() const { return Get("Framedata"); }

        // Avatar settings
        inline const char* Avatar_settings() const { return Get("Avatar settings"); }

        // Controller Settings
        inline const char* Controller_Settings() const { return Get("Controller Settings"); }

        // Local Controller Override
        inline const char* Local_Controller_Override() const { return Get("Local Controller Override"); }

        // Controller_override_help
        inline const char* Controller_override_help() const { return Get("Controller_override_help"); }

        // Refresh controllers
        inline const char* Refresh_controllers() const { return Get("Refresh controllers"); }

        // Controller_refresh_help
        inline const char* Controller_refresh_help() const { return Get("Controller_refresh_help"); }

        // Open Joy.cpl
        inline const char* Open_Joy_cpl() const { return Get("Open Joy.cpl"); }

        // Auto-refresh
        inline const char* Auto_refresh() const { return Get("Auto-refresh"); }

        // Auto_refresh_warning
        inline const char* Auto_refresh_warning() const { return Get("Auto_refresh_warning"); }

        // No input devices detected.
        inline const char* No_input_devices_detected() const { return Get("No input devices detected."); }

        // STEAM INPUT: %s
        inline const char* STEAM_INPUT_s() const { return Get("STEAM INPUT: %s"); }

        // ON
        inline const char* ON() const { return Get("ON"); }

        // OFF
        inline const char* OFF() const { return Get("OFF"); }

        // Steam_input_active_notice
        inline const char* Steam_input_active_notice() const { return Get("Steam_input_active_notice"); }

        // Steam_input_limitations
        inline const char* Steam_input_limitations() const { return Get("Steam_input_limitations"); }

        // Swap P1 Controller to P2
        inline const char* Swap_P1_Controller_to_P2() const { return Get("Swap P1 Controller to P2"); }

        // Controller_swap_hint
        inline const char* Controller_swap_hint() const { return Get("Controller_swap_hint"); }

        // Multiple keyboards override
        inline const char* Multiple_keyboards_override() const { return Get("Multiple keyboards override"); }

        // Keyboard_player1_help
        inline const char* Keyboard_player1_help() const { return Get("Keyboard_player1_help"); }

        // No keyboards selected
        inline const char* No_keyboards_selected() const { return Get("No keyboards selected"); }

        // No keyboards detected.
        inline const char* No_keyboards_detected() const { return Get("No keyboards detected."); }

        // P1 Keyboards
        inline const char* P1_Keyboards() const { return Get("P1 Keyboards"); }

        // Map
        inline const char* Map() const { return Get("Map"); }

        // Rename
        inline const char* Rename() const { return Get("Rename"); }

        // Ignore
        inline const char* Ignore() const { return Get("Ignore"); }

        // Rename keyboard
        inline const char* Rename_keyboard() const { return Get("Rename keyboard"); }

        // Set a custom name for this keyboard.
        inline const char* Set_a_custom_name_for_this_keyboard() const { return Get("Set a custom name for this keyboard."); }

        // Save
        inline const char* Save() const { return Get("Save"); }

        // Cancel
        inline const char* Cancel() const { return Get("Cancel"); }

        // Clear
        inline const char* Clear() const { return Get("Clear"); }

        // Configure keyboard mapping
        inline const char* Configure_keyboard_mapping() const { return Get("Configure keyboard mapping"); }

        // Unbound
        inline const char* Unbound() const { return Get("Unbound"); }

        // Press a key...
        inline const char* Press_a_key() const { return Get("Press a key..."); }

        // Select game mode:
        inline const char* Select_game_mode() const { return Get("Select game mode:"); }

        // Stage
        inline const char* Stage() const { return Get("Stage"); }

        // Player 1
        inline const char* Player_1() const { return Get("Player 1"); }

        // Gap:
        inline const char* Gap() const { return Get("Gap:"); }

        // Advantage:
        inline const char* Advantage() const { return Get("Advantage:"); }

        // Player 2
        inline const char* Player_2() const { return Get("Player 2"); }

        // Player 1:
        inline const char* Player_1_2() const { return Get("Player 1:"); }

        // Player 2:
        inline const char* Player_2_2() const { return Get("Player 2:"); }

        // Copy to clipboard
        inline const char* Copy_to_clipboard() const { return Get("Copy to clipboard"); }

        // Search
        inline const char* Search() const { return Get("Search"); }

        // System_log_copied
        inline const char* System_log_copied() const { return Get("System_log_copied"); }

        // Reload custom palettes
        inline const char* Reload_custom_palettes() const { return Get("Reload custom palettes"); }

        // Select character
        inline const char* Select_character() const { return Get("Select character"); }

        // Select palette
        inline const char* Select_palette() const { return Get("Select palette"); }

        // Select file
        inline const char* Select_file() const { return Get("Select file"); }

        // Gradient generator
        inline const char* Gradient_generator() const { return Get("Gradient generator"); }

        // Undo
        inline const char* Undo() const { return Get("Undo"); }

        // Redo
        inline const char* Redo() const { return Get("Redo"); }

        // Cannot save with Highlight mode on!
        inline const char* Cannot_save_with_Highlight_mode_on() const { return Get("Cannot save with Highlight mode on!"); }

        // Save with bloom effect
        inline const char* Save_with_bloom_effect() const { return Get("Save with bloom effect"); }

        // Bloom effects cannot be changed until a new round is started
        inline const char* Bloom_effects_cannot_be_changed_until_a_new_round_is_started() const { return Get("Bloom effects cannot be changed until a new round is started"); }

        // Palette name:
        inline const char* Palette_name() const { return Get("Palette name:"); }

        // Creator (optional):
        inline const char* Creator_optional() const { return Get("Creator (optional):"); }

        // Palette description (optional):
        inline const char* Palette_description_optional() const { return Get("Palette description (optional):"); }

        // Save palette
        inline const char* Save_palette() const { return Get("Save palette"); }

        // Error, no filename given
        inline const char* Error_no_filename_given() const { return Get("Error, no filename given"); }

        // Error, not a valid filename
        inline const char* Error_not_a_valid_filename() const { return Get("Error, not a valid filename"); }

        // '%s' saved successfully
        inline const char* s_saved_successfully() const { return Get("'%s' saved successfully"); }

        // '%s' save failed
        inline const char* s_save_failed() const { return Get("'%s' save failed"); }

        // Overwrite_confirmation_prompt
        inline const char* Overwrite_confirmation_prompt() const { return Get("Overwrite_confirmation_prompt"); }

        // OK
        inline const char* OK() const { return Get("OK"); }

        // Reset palette
        inline const char* Reset_palette() const { return Get("Reset palette"); }

        // Out of bounds
        inline const char* Out_of_bounds() const { return Get("Out of bounds"); }

        // ONLINE PALETTE
        inline const char* ONLINE_PALETTE() const { return Get("ONLINE PALETTE"); }

        // Creator: %s
        inline const char* Creator_s() const { return Get("Creator: %s"); }

        // Description: %s
        inline const char* Description_s() const { return Get("Description: %s"); }

        // Has bloom effect
        inline const char* Has_bloom_effect() const { return Get("Has bloom effect"); }

        // Random selection
        inline const char* Random_selection() const { return Get("Random selection"); }

        // Start index
        inline const char* Start_index() const { return Get("Start index"); }

        // End index
        inline const char* End_index() const { return Get("End index"); }

        // Start color
        inline const char* Start_color() const { return Get("Start color"); }

        // End color
        inline const char* End_color() const { return Get("End color"); }

        // Swap colors
        inline const char* Swap_colors() const { return Get("Swap colors"); }

        // Generate gradient
        inline const char* Generate_gradient() const { return Get("Generate gradient"); }

        // Refresh
        inline const char* Refresh() const { return Get("Refresh"); }

        // Recording side: %c
        inline const char* Recording_side_c() const { return Get("Recording side: %c"); }

        // Switch recording side
        inline const char* Switch_recording_side() const { return Get("Switch recording side"); }

        // Add/Remove
        inline const char* Add_Remove() const { return Get("Add/Remove"); }

        // Frame
        inline const char* Frame() const { return Get("Frame"); }

        // Literal
        inline const char* Literal() const { return Get("Literal"); }

        // Command
        inline const char* Command() const { return Get("Command"); }

        // Edit Input
        inline const char* Edit_Input() const { return Get("Edit Input"); }

        // Direction
        inline const char* Direction() const { return Get("Direction"); }

        // Bind
        inline const char* Bind() const { return Get("Bind"); }

        // Menu action
        inline const char* Menu_action() const { return Get("Menu action"); }

        // Battle action
        inline const char* Battle_action() const { return Get("Battle action"); }

        // Close
        inline const char* Close() const { return Get("Close"); }

        // Set all to default
        inline const char* Set_all_to_default() const { return Get("Set all to default"); }

        // Ignored keyboards
        inline const char* Ignored_keyboards() const { return Get("Ignored keyboards"); }

        // No ignored keyboards.
        inline const char* No_ignored_keyboards() const { return Get("No ignored keyboards."); }

        // Unignore
        inline const char* Unignore() const { return Get("Unignore"); }

        // (connected)
        inline const char* connected() const { return Get("(connected)"); }

        // (not connected)
        inline const char* not_connected() const { return Get("(not connected)"); }

        // Mapping for %s
        inline const char* Mapping_for_s() const { return Get("Mapping for %s"); }

        // Test
        inline const char* Test() const { return Get("Test"); }

        // Player 1 Controller
        inline const char* Player_1_Controller() const { return Get("Player 1 Controller"); }

        // Player 2 Controller
        inline const char* Player_2_Controller() const { return Get("Player 2 Controller"); }

        // Loaded settings.ini values
        inline const char* Loaded_settings_ini_values() const { return Get("Loaded settings.ini values"); }

        // Current online players:
        inline const char* Current_online_players() const { return Get("Current online players:"); }

        // <No data>
        inline const char* No_data() const { return Get("<No data>"); }

        // Avatar
        inline const char* Avatar() const { return Get("Avatar"); }

        // Color
        inline const char* Color() const { return Get("Color"); }

        // Accessory 1
        inline const char* Accessory_1() const { return Get("Accessory 1"); }

        // Accessory 2
        inline const char* Accessory_2() const { return Get("Accessory 2"); }

        // CONNECT TO NETWORK MODE FIRST
        inline const char* CONNECT_TO_NETWORK_MODE_FIRST() const { return Get("CONNECT TO NETWORK MODE FIRST"); }

        // FrameHistory help
        inline const char* FrameHistory_help() const { return Get("FrameHistory help"); }

        // FrameHistory auto reset help
        inline const char* FrameHistory_auto_reset_help() const { return Get("FrameHistory auto reset help"); }

        // Count empty frames##framehistory
        inline const char* Count_empty_frames_framehistory() const { return Get("Count empty frames##framehistory"); }

        // FrameHistory count empty frames help
        inline const char* FrameHistory_count_empty_frames_help() const { return Get("FrameHistory count empty frames help"); }

        // Box width
        inline const char* Box_width() const { return Get("Box width"); }

        // Box height
        inline const char* Box_height() const { return Get("Box height"); }

        // spacing
        inline const char* spacing() const { return Get("spacing"); }

        // Enable##framehistory_section
        inline const char* Enable_framehistory_section() const { return Get("Enable##framehistory_section"); }

        // Auto Reset##Reset after each idle frame
        inline const char* Auto_Reset_Reset_after_each_idle_frame() const { return Get("Auto Reset##Reset after each idle frame"); }

        // Enable##framedata_section
        inline const char* Enable_framedata_section() const { return Get("Enable##framedata_section"); }

        // Advantage on stagger hit
        inline const char* Advantage_on_stagger_hit() const { return Get("Advantage on stagger hit"); }

        // YOU ARE NOT IN MATCH!
        inline const char* YOU_ARE_NOT_IN_MATCH() const { return Get("YOU ARE NOT IN MATCH!"); }

        // YOU ARE NOT IN TRAINING MODE OR REPLAY THEATER!
        inline const char* YOU_ARE_NOT_IN_TRAINING_MODE_OR_REPLAY_THEATER() const { return Get("YOU ARE NOT IN TRAINING MODE OR REPLAY THEATER!"); }

        // YOU ARE NOT IN A MATCH, IN TRAINING MODE OR REPLAY THEATER!
        inline const char* YOU_ARE_NOT_IN_A_MATCH_IN_TRAINING_MODE_OR_REPLAY_THEATER() const { return Get("YOU ARE NOT IN A MATCH, IN TRAINING MODE OR REPLAY THEATER!"); }

        // THERE WAS AN ERROR LOADING ONE/BOTH OF THE CHARACTERS
        inline const char* THERE_WAS_AN_ERROR_LOADING_ONE_BOTH_OF_THE_CHARACTERS() const { return Get("THERE WAS AN ERROR LOADING ONE/BOTH OF THE CHARACTERS"); }

        // Palette editor
        inline const char* Palette_editor() const { return Get("Palette editor"); }

        // YOU ARE NOT IN MATCH! (Replay)
        inline const char* YOU_ARE_NOT_IN_MATCH_Replay() const { return Get("YOU ARE NOT IN MATCH! (Replay)"); }

        // YOU ARE NOT IN REPLAY MENU!
        inline const char* YOU_ARE_NOT_IN_REPLAY_MENU() const { return Get("YOU ARE NOT IN REPLAY MENU!"); }

        // YOU ARE NOT IN CHARACTER SELECTION!
        inline const char* YOU_ARE_NOT_IN_CHARACTER_SELECTION() const { return Get("YOU ARE NOT IN CHARACTER SELECTION!"); }

        // Hide HUD
        inline const char* Hide_HUD() const { return Get("Hide HUD"); }

        // Toggle Rewind
        inline const char* Toggle_Rewind() const { return Get("Toggle Rewind"); }

        // Replay Database
        inline const char* Replay_Database() const { return Get("Replay Database"); }

        // Enable/Disable Automatic Replay Uploads?
        inline const char* Enable_Disable_Automatic_Replay_Uploads() const { return Get("Enable/Disable Automatic Replay Uploads?"); }

        // Main window notification format
        inline const char* Main_window_notification_format() const { return Get("Main window notification format"); }

        // Replay_uploads_description
        inline const char* Replay_uploads_description() const { return Get("Replay_uploads_description"); }

        // Enable/Disable Upload
        inline const char* Enable_Disable_Upload() const { return Get("Enable/Disable Upload"); }

        // Discord
        inline const char* Discord() const { return Get("Discord"); }

        // Forum
        inline const char* Forum() const { return Get("Forum"); }

        // GitHub
        inline const char* GitHub() const { return Get("GitHub"); }

        // Player1
        inline const char* Player1() const { return Get("Player1"); }

        // Player2
        inline const char* Player2() const { return Get("Player2"); }

        // Draw hitbox/hurtbox
        inline const char* Draw_hitbox_hurtbox() const { return Get("Draw hitbox/hurtbox"); }

        // Draw origin
        inline const char* Draw_origin() const { return Get("Draw origin"); }

        // Draw collision
        inline const char* Draw_collision() const { return Get("Draw collision"); }

        // Draw throw/range boxes
        inline const char* Draw_throw_range_boxes() const { return Get("Draw throw/range boxes"); }

        // Origin_point_note
        inline const char* Origin_point_note() const { return Get("Origin_point_note"); }

        // Collision_box_note
        inline const char* Collision_box_note() const { return Get("Collision_box_note"); }

        // Throw range help
        inline const char* Throw_range_help() const { return Get("Throw range help"); }

        // Freeze frame:
        inline const char* Freeze_frame() const { return Get("Freeze frame:"); }

        // Frame Count
        inline const char* Frame_Count() const { return Get("Frame Count"); }

        // Reset
        inline const char* Reset() const { return Get("Reset"); }

        // Freeze animation
        inline const char* Freeze_animation() const { return Get("Freeze animation"); }

        // Stop timer
        inline const char* Stop_timer() const { return Get("Stop timer"); }

        // Step frames
        inline const char* Step_frames() const { return Get("Step frames"); }

        // YOU ARE NOT IN TRAINING, VERSUS, OR REPLAY!
        inline const char* YOU_ARE_NOT_IN_TRAINING_VERSUS_OR_REPLAY() const { return Get("YOU ARE NOT IN TRAINING, VERSUS, OR REPLAY!"); }

        // Game Mode
        inline const char* Game_Mode() const { return Get("Game Mode"); }

        // Enable##hitbox_overlay_section
        inline const char* Enable_hitbox_overlay_section() const { return Get("Enable##hitbox_overlay_section"); }

        // Custom palette reload
        inline const char* Custom_palette_reload() const { return Get("Custom palette reload"); }

        // Enable##framehistory_section checkbox
        inline const char* Enable_framehistory_section_checkbox() const { return Get("Enable##framehistory_section checkbox"); }

        // Draw hitbox/hurtbox##hitbox_overlay_section
        inline const char* Draw_hitbox_hurtbox_hitbox_overlay_section() const { return Get("Draw hitbox/hurtbox##hitbox_overlay_section"); }

        // Draw origin##hitbox_overlay_section
        inline const char* Draw_origin_hitbox_overlay_section() const { return Get("Draw origin##hitbox_overlay_section"); }

        // Draw collision##hitbox_overlay_section
        inline const char* Draw_collision_hitbox_overlay_section() const { return Get("Draw collision##hitbox_overlay_section"); }

        // Step frames##hitbox_overlay_section
        inline const char* Step_frames_hitbox_overlay_section() const { return Get("Step frames##hitbox_overlay_section"); }

        // Gameplay settings header
        inline const char* Gameplay_settings_header() const { return Get("Gameplay settings header"); }

        // Hide HUD checkbox
        inline const char* Hide_HUD_checkbox() const { return Get("Hide HUD checkbox"); }

        // States
        inline const char* States() const { return Get("States"); }

        // Log
        inline const char* Log() const { return Get("Log"); }

        // Replay Rewind
        inline const char* Replay_Rewind() const { return Get("Replay Rewind"); }

        // Replay Upload
        inline const char* Replay_Upload() const { return Get("Replay Upload"); }

        // Enable##framehistory_section label
        inline const char* Enable_framehistory_section_label() const { return Get("Enable##framehistory_section label"); }

        // Auto Reset label
        inline const char* Auto_Reset_label() const { return Get("Auto Reset label"); }

        // FrameHistory width label
        inline const char* FrameHistory_width_label() const { return Get("FrameHistory width label"); }

        // FrameHistory height label
        inline const char* FrameHistory_height_label() const { return Get("FrameHistory height label"); }

        // FrameHistory spacing label
        inline const char* FrameHistory_spacing_label() const { return Get("FrameHistory spacing label"); }

        // FrameHistory not enabled message
        inline const char* FrameHistory_not_enabled_message() const { return Get("FrameHistory not enabled message"); }

        // FrameHistory character load error
        inline const char* FrameHistory_character_load_error() const { return Get("FrameHistory character load error"); }

        // Language
        inline const char* Language() const { return Get("Language"); }

        // Language incomplete label
        inline const char* Language_incomplete_label() const { return Get("Language incomplete label"); }

        // Language selection help
        inline const char* Language_selection_help() const { return Get("Language selection help"); }

        // Active entities: %d
        inline const char* Active_entities_d() const { return Get("Active entities: %d"); }

        // Active entities with unk_status2 = 2: %d
        inline const char* Active_entities_with_unk_status2_2_d() const { return Get("Active entities with unk_status2 = 2: %d"); }

        // Only works during a running replay
        inline const char* Only_works_during_a_running_replay() const { return Get("Only works during a running replay"); }

        // Rewind
        inline const char* Rewind() const { return Get("Rewind"); }

        // Replay rewind help tooltip
        inline const char* Replay_rewind_help_tooltip() const { return Get("Replay rewind help tooltip"); }

        // Rewind Interval
        inline const char* Rewind_Interval() const { return Get("Rewind Interval"); }

        // Rewind interval help tooltip
        inline const char* Rewind_interval_help_tooltip() const { return Get("Rewind interval help tooltip"); }

        // 1s
        inline const char* _1s() const { return Get("1s"); }

        // 3s
        inline const char* _3s() const { return Get("3s"); }

        // 9s
        inline const char* _9s() const { return Get("9s"); }

        // Saved Checkpoints Adv. Info
        inline const char* Saved_Checkpoints_Adv_Info() const { return Get("Saved Checkpoints Adv. Info"); }

        // Rewind pos: +%d
        inline const char* Rewind_pos_d() const { return Get("Rewind pos: +%d"); }

        // snap_apparatus snapshot_count: %d
        inline const char* snap_apparatus_snapshot_count_d() const { return Get("snap_apparatus snapshot_count: %d"); }

        // %d: Framecount:%d
        inline const char* d_Framecount_d() const { return Get("%d: Framecount:%d"); }

        // Ranked_search_warning
        inline const char* Ranked_search_warning() const { return Get("Ranked_search_warning"); }

        // Network Matches
        inline const char* Network_Matches() const { return Get("Network Matches"); }

        // Ranked Matches
        inline const char* Ranked_Matches() const { return Get("Ranked Matches"); }

        // Show ranked progress
        inline const char* Show_ranked_progress() const { return Get("Show ranked progress"); }

        // Shows a movable ranked progress window during ranked character select, ranked menu flow, and after a successful ranked LP upload.
        inline const char* Shows_a_movable_ranked_progress_window_during_ranked_character_select_ranked_menu_flow_and_after_a_successful_ranked_LP_upload() const { return Get("Shows a movable ranked progress window during ranked character select, ranked menu flow, and after a successful ranked LP upload."); }

        // Show square color progress
        inline const char* Show_square_color_progress() const { return Get("Show square color progress"); }

        // Shows a movable network square color progress window while inside network mode.
        inline const char* Shows_a_movable_network_square_color_progress_window_while_inside_network_mode() const { return Get("Shows a movable network square color progress window while inside network mode."); }

        // Show ranked prediction
        inline const char* Show_ranked_prediction() const { return Get("Show ranked prediction"); }

        // Shows win/loss ranked outcome predictions during ranked match confirmation and ranked rematch screens when opponent rank data is available.
        inline const char* Shows_win_loss_ranked_outcome_predictions_during_ranked_match_confirmation_and_ranked_rematch_screens_when_opponent_rank_data_is_available() const { return Get("Shows win/loss ranked outcome predictions during ranked match confirmation and ranked rematch screens when opponent rank data is available."); }

        // Ranked ladder
        inline const char* Ranked_ladder() const { return Get("Ranked ladder"); }

        // Ranked ladder###RankedLadder
        inline const char* Ranked_ladder_RankedLadder() const { return Get("Ranked ladder###RankedLadder"); }

        // Opens the ranked ladder window, including known LP thresholds and population estimates.
        inline const char* Opens_the_ranked_ladder_window_including_known_LP_thresholds_and_population_estimates() const { return Get("Opens the ranked ladder window, including known LP thresholds and population estimates."); }

        // Ranked Progress
        inline const char* Ranked_Progress() const { return Get("Ranked Progress"); }

        // Ranked Progress###RankedProgressOverlay
        inline const char* Ranked_Progress_RankedProgressOverlay() const { return Get("Ranked Progress###RankedProgressOverlay"); }

        // Choose a character and open a closable ranked progress window. Right-click the ranked progress window to configure the top label.
        inline const char* Choose_a_character_and_open_a_closable_ranked_progress_window_Right_click_the_ranked_progress_window_to_configure_the_top_label() const { return Get("Choose a character and open a closable ranked progress window. Right-click the ranked progress window to configure the top label."); }

        // How does ranked work?
        inline const char* How_does_ranked_work() const { return Get("How does ranked work?"); }

        // Choose any rank and open an explanation of its LP, promotion, and demotion rules.
        inline const char* Choose_any_rank_and_open_an_explanation_of_its_LP_promotion_and_demotion_rules() const { return Get("Choose any rank and open an explanation of its LP, promotion, and demotion rules."); }

        // Select ranked character###RankedProgressCharacterSelector
        inline const char* Select_ranked_character_RankedProgressCharacterSelector() const { return Get("Select ranked character###RankedProgressCharacterSelector"); }

        // Ranked Prediction###RankedPredictionOverlay
        inline const char* Ranked_Prediction_RankedPredictionOverlay() const { return Get("Ranked Prediction###RankedPredictionOverlay"); }

        // Opponent
        inline const char* Opponent() const { return Get("Opponent"); }

        // Waiting for opponent...
        inline const char* Waiting_for_opponent() const { return Get("Waiting for opponent..."); }

        // Loading rank...
        inline const char* Loading_rank() const { return Get("Loading rank..."); }

        // Rank unavailable
        inline const char* Rank_unavailable() const { return Get("Rank unavailable"); }

        // RANK UP
        inline const char* RANK_UP() const { return Get("RANK UP"); }

        // RANK DOWN
        inline const char* RANK_DOWN() const { return Get("RANK DOWN"); }

        // Nothing.
        inline const char* Nothing() const { return Get("Nothing."); }

        // Unknown
        inline const char* Unknown() const { return Get("Unknown"); }

        // Current rank data unavailable
        inline const char* Current_rank_data_unavailable() const { return Get("Current rank data unavailable"); }

        // Can only rank up against your rank or higher.
        inline const char* Can_only_rank_up_against_your_rank_or_higher() const { return Get("Can only rank up against your rank or higher."); }

        // LP Threshold Reached
        inline const char* LP_Threshold_Reached() const { return Get("LP Threshold Reached"); }

        // Automatic Promotion Reached
        inline const char* Automatic_Promotion_Reached() const { return Get("Automatic Promotion Reached"); }

        // LP already capped for this opponent.
        inline const char* LP_already_capped_for_this_opponent() const { return Get("LP already capped for this opponent."); }

        // LV1-LV10 losses do not change LP.
        inline const char* LV1_LV10_losses_do_not_change_LP() const { return Get("LV1-LV10 losses do not change LP."); }

        // Automatic Demotion Reached
        inline const char* Automatic_Demotion_Reached() const { return Get("Automatic Demotion Reached"); }

        // Waiting for ranked opponent data.
        inline const char* Waiting_for_ranked_opponent_data() const { return Get("Waiting for ranked opponent data."); }

        // Waiting for character leaderboard lookup.
        inline const char* Waiting_for_character_leaderboard_lookup() const { return Get("Waiting for character leaderboard lookup."); }

        // Opponent character leaderboard entry unavailable.
        inline const char* Opponent_character_leaderboard_entry_unavailable() const { return Get("Opponent character leaderboard entry unavailable."); }

        // Waiting for opponent character data.
        inline const char* Waiting_for_opponent_character_data() const { return Get("Waiting for opponent character data."); }

        // Scanning... %d probes fired
        inline const char* Scanning_d_probes_fired() const { return Get("Scanning... %d probes fired"); }

        // Total ranked players: %u  |  Samples: %u
        inline const char* Total_ranked_players_u_Samples_u() const { return Get("Total ranked players: %u  |  Samples: %u"); }

        // Distribution search failed.
        inline const char* Distribution_search_failed() const { return Get("Distribution search failed."); }

        // Waiting for leaderboard handle...
        inline const char* Waiting_for_leaderboard_handle() const { return Get("Waiting for leaderboard handle..."); }

        // Opening ladder begins scan.
        inline const char* Opening_ladder_begins_scan() const { return Get("Opening ladder begins scan."); }

        // Players
        inline const char* Players() const { return Get("Players"); }

        // Ignored
        inline const char* Ignored() const { return Get("Ignored"); }

        // Loading
        inline const char* Loading() const { return Get("Loading"); }

        // No ranked progress data available.
        inline const char* No_ranked_progress_data_available() const { return Get("No ranked progress data available."); }

        // Show matches
        inline const char* Show_matches() const { return Get("Show matches"); }

        // Show wins
        inline const char* Show_wins() const { return Get("Show wins"); }

        // Show losses
        inline const char* Show_losses() const { return Get("Show losses"); }

        // Show winrate %
        inline const char* Show_winrate() const { return Get("Show winrate %"); }

        // Show character leaderboard placement
        inline const char* Show_character_leaderboard_placement() const { return Get("Show character leaderboard placement"); }

        // Show global leaderboard placement
        inline const char* Show_global_leaderboard_placement() const { return Get("Show global leaderboard placement"); }

        // Matches
        inline const char* Matches() const { return Get("Matches"); }

        // Wins
        inline const char* Wins() const { return Get("Wins"); }

        // Losses
        inline const char* Losses() const { return Get("Losses"); }

        // in
        inline const char* in() const { return Get("in"); }

        // Leaderboard
        inline const char* Leaderboard() const { return Get("Leaderboard"); }

        // in Global Leaderboard
        inline const char* in_Global_Leaderboard() const { return Get("in Global Leaderboard"); }

        // Demotion %u/%u
        inline const char* Demotion_u_u() const { return Get("Demotion %u/%u"); }

        // Promotion %u/%u
        inline const char* Promotion_u_u() const { return Get("Promotion %u/%u"); }

        // How does my rank work?
        inline const char* How_does_my_rank_work() const { return Get("How does my rank work?"); }

        // How does my rank work?###RankedRulesDialog
        inline const char* How_does_my_rank_work_RankedRulesDialog() const { return Get("How does my rank work?###RankedRulesDialog"); }

        // Check another rank's rules
        inline const char* Check_another_rank_s_rules() const { return Get("Check another rank's rules"); }

        // Check another rank's rules###RankedRulesSelector
        inline const char* Check_another_rank_s_rules_RankedRulesSelector() const { return Get("Check another rank's rules###RankedRulesSelector"); }

        // Check a rank's rules###RankedRulesSelector
        inline const char* Check_a_rank_s_rules_RankedRulesSelector() const { return Get("Check a rank's rules###RankedRulesSelector"); }

        // Compare this with another rank
        inline const char* Compare_this_with_another_rank() const { return Get("Compare this with another rank"); }

        // Compare this with another rank###RankedRulesCompareSelector
        inline const char* Compare_this_with_another_rank_RankedRulesCompareSelector() const { return Get("Compare this with another rank###RankedRulesCompareSelector"); }

        // Rank comparison###RankedRulesComparison
        inline const char* Rank_comparison_RankedRulesComparison() const { return Get("Rank comparison###RankedRulesComparison"); }

        // Detected differences
        inline const char* Detected_differences() const { return Get("Detected differences"); }

        // vs
        inline const char* vs() const { return Get("vs"); }

        // Show rules
        inline const char* Show_rules() const { return Get("Show rules"); }

        // Rank
        inline const char* Rank() const { return Get("Rank"); }

        // Win
        inline const char* Win() const { return Get("Win"); }

        // Loss
        inline const char* Loss() const { return Get("Loss"); }

        // Opponent Rank
        inline const char* Opponent_Rank() const { return Get("Opponent Rank"); }

        // Your rank rules
        inline const char* Your_rank_rules() const { return Get("Your rank rules"); }

        // LP table
        inline const char* LP_table() const { return Get("LP table"); }

        // ANY RANK
        inline const char* ANY_RANK() const { return Get("ANY RANK"); }

        // The same type of rules as this rank apply from %s to %s.
        inline const char* The_same_type_of_rules_as_this_rank_apply_from_s_to_s() const { return Get("The same type of rules as this rank apply from %s to %s."); }

        // (resets Demotion Counter)
        inline const char* resets_Demotion_Counter() const { return Get("(resets Demotion Counter)"); }

        // (resets Promotion Counter)
        inline const char* resets_Promotion_Counter() const { return Get("(resets Promotion Counter)"); }

        // LV1-LV10 rules
        inline const char* LV1_LV10_rules() const { return Get("LV1-LV10 rules"); }

        // LV11-LV14 rules
        inline const char* LV11_LV14_rules() const { return Get("LV11-LV14 rules"); }

        // LV15-LV18 rules
        inline const char* LV15_LV18_rules() const { return Get("LV15-LV18 rules"); }

        // LV19-LV23 rules
        inline const char* LV19_LV23_rules() const { return Get("LV19-LV23 rules"); }

        // LV24-LV28 rules
        inline const char* LV24_LV28_rules() const { return Get("LV24-LV28 rules"); }

        // LV29-LV33 rules
        inline const char* LV29_LV33_rules() const { return Get("LV29-LV33 rules"); }

        // LV34 rules
        inline const char* LV34_rules() const { return Get("LV34 rules"); }

        // LV35 rules
        inline const char* LV35_rules() const { return Get("LV35 rules"); }

        // Leader rules
        inline const char* Leader_rules() const { return Get("Leader rules"); }

        // Hero rules
        inline const char* Hero_rules() const { return Get("Hero rules"); }

        // Kisshin rules
        inline const char* Kisshin_rules() const { return Get("Kisshin rules"); }

        // Hades rules
        inline const char* Hades_rules() const { return Get("Hades rules"); }

        // Ruler rules
        inline const char* Ruler_rules() const { return Get("Ruler rules"); }

        // %s - %s
        inline const char* s_s() const { return Get("%s - %s"); }

        // %s (%s)
        inline const char* s_s_2() const { return Get("%s (%s)"); }

        // %+d LP
        inline const char* d_LP() const { return Get("%+d LP"); }

        //  (%+d Promotion Counter)
        inline const char* d_Promotion_Counter() const { return Get(" (%+d Promotion Counter)"); }

        // %+d LP (%+d Promotion Counter)
        inline const char* d_LP_d_Promotion_Counter() const { return Get("%+d LP (%+d Promotion Counter)"); }

        // %+d LP (+1 Demotion Counter)
        inline const char* d_LP_1_Demotion_Counter() const { return Get("%+d LP (+1 Demotion Counter)"); }

        //  or higher.
        inline const char* or_higher() const { return Get(" or higher."); }

        // or higher.
        inline const char* or_higher_2() const { return Get("or higher."); }

        // If you reach %u LP, you'll rank up to %s.
        inline const char* If_you_reach_u_LP_you_ll_rank_up_to_s() const { return Get("If you reach %u LP, you'll rank up to %s."); }

        // At this rank, a win against a lower rank can fill the LP bar, but the rank-up only happens when you beat %s or higher.
        inline const char* At_this_rank_a_win_against_a_lower_rank_can_fill_the_LP_bar_but_the_rank_up_only_happens_when_you_beat_s_or_higher() const { return Get("At this rank, a win against a lower rank can fill the LP bar, but the rank-up only happens when you beat %s or higher."); }

        // This is the highest rank covered by the current known rules.
        inline const char* This_is_the_highest_rank_covered_by_the_current_known_rules() const { return Get("This is the highest rank covered by the current known rules."); }

        // If you fall to %u LP, you'll rank down to %s.
        inline const char* If_you_fall_to_u_LP_you_ll_rank_down_to_s() const { return Get("If you fall to %u LP, you'll rank down to %s."); }

        // LP losses do not directly rank you down in this rank.
        inline const char* LP_losses_do_not_directly_rank_you_down_in_this_rank() const { return Get("LP losses do not directly rank you down in this rank."); }

        // +1 Demotion Counter
        inline const char* _1_Demotion_Counter() const { return Get("+1 Demotion Counter"); }

        // If you lose against anyone in this range (%s), you'll get +1 Demotion Counter. At %d, you'll rank down to %s.
        inline const char* If_you_lose_against_anyone_in_this_range_s_you_ll_get_1_Demotion_Counter_At_d_you_ll_rank_down_to_s() const { return Get("If you lose against anyone in this range (%s), you'll get +1 Demotion Counter. At %d, you'll rank down to %s."); }

        // This rank does not use a demotion counter.
        inline const char* This_rank_does_not_use_a_demotion_counter() const { return Get("This rank does not use a demotion counter."); }

        // Demotion Counter
        inline const char* Demotion_Counter() const { return Get("Demotion Counter"); }

        // Promotion Counter
        inline const char* Promotion_Counter() const { return Get("Promotion Counter"); }

        // If you win against anyone in this range (%s), you'll add points to your Promotion Counter.
        inline const char* If_you_win_against_anyone_in_this_range_s_you_ll_add_points_to_your_Promotion_Counter() const { return Get("If you win against anyone in this range (%s), you'll add points to your Promotion Counter."); }

        // If your Promotion Counter reaches %d before the LP bar fills, you'll rank up to %s.
        inline const char* If_your_Promotion_Counter_reaches_d_before_the_LP_bar_fills_you_ll_rank_up_to_s() const { return Get("If your Promotion Counter reaches %d before the LP bar fills, you'll rank up to %s."); }

        // This rank does not use a promotion counter.
        inline const char* This_rank_does_not_use_a_promotion_counter() const { return Get("This rank does not use a promotion counter."); }

        // This table shows what the game predicts from one match at this rank. Counter notes only appear when that counter can move.
        inline const char* This_table_shows_what_the_game_predicts_from_one_match_at_this_rank_Counter_notes_only_appear_when_that_counter_can_move() const { return Get("This table shows what the game predicts from one match at this rank. Counter notes only appear when that counter can move."); }

        // Remember that not every rank works exactly like this. These are only the rules for %s.
        inline const char* Remember_that_not_every_rank_works_exactly_like_this_These_are_only_the_rules_for_s() const { return Get("Remember that not every rank works exactly like this. These are only the rules for %s."); }

        // rank
        inline const char* rank_2() const { return Get("rank"); }

        // to
        inline const char* to() const { return Get("to"); }

        // If you get above
        inline const char* If_you_get_above() const { return Get("If you get above"); }

        // , you'll rank up to
        inline const char* you_ll_rank_up_to() const { return Get(", you'll rank up to"); }

        // At this rank, a win against a lower rank can fill the LP bar, but the rank-up only happens when you beat
        inline const char* At_this_rank_a_win_against_a_lower_rank_can_fill_the_LP_bar_but_the_rank_up_only_happens_when_you_beat() const { return Get("At this rank, a win against a lower rank can fill the LP bar, but the rank-up only happens when you beat"); }

        // If you get below
        inline const char* If_you_get_below() const { return Get("If you get below"); }

        // , you'll rank down to
        inline const char* you_ll_rank_down_to() const { return Get(", you'll rank down to"); }

        // If you lose against anyone that is from
        inline const char* If_you_lose_against_anyone_that_is_from() const { return Get("If you lose against anyone that is from"); }

        // , you'll get
        inline const char* you_ll_get() const { return Get(", you'll get"); }

        // . At
        inline const char* At() const { return Get(". At"); }

        // Your
        inline const char* Your() const { return Get("Your"); }

        // resets by winning a ranked match against anyone that is from
        inline const char* resets_by_winning_a_ranked_match_against_anyone_that_is_from() const { return Get("resets by winning a ranked match against anyone that is from"); }

        // If you win against anyone that is from
        inline const char* If_you_win_against_anyone_that_is_from() const { return Get("If you win against anyone that is from"); }

        // , you'll add points to your
        inline const char* you_ll_add_points_to_your() const { return Get(", you'll add points to your"); }

        // resets by losing against anyone that is from
        inline const char* resets_by_losing_against_anyone_that_is_from() const { return Get("resets by losing against anyone that is from"); }

        // Remember that not every rank works exactly like this. These are only the rules for
        inline const char* Remember_that_not_every_rank_works_exactly_like_this_These_are_only_the_rules_for() const { return Get("Remember that not every rank works exactly like this. These are only the rules for"); }

        // none
        inline const char* none() const { return Get("none"); }

        // LP range is
        inline const char* LP_range_is() const { return Get("LP range is"); }

        // %s has a bigger LP range by %u LP.
        inline const char* s_has_a_bigger_LP_range_by_u_LP() const { return Get("%s has a bigger LP range by %u LP."); }

        // has a bigger LP range by %u LP.
        inline const char* has_a_bigger_LP_range_by_u_LP() const { return Get("has a bigger LP range by %u LP."); }

        // can fill its LP bar against lower ranks, but can only rank up by beating its own rank or higher.
        inline const char* can_fill_its_LP_bar_against_lower_ranks_but_can_only_rank_up_by_beating_its_own_rank_or_higher() const { return Get("can fill its LP bar against lower ranks, but can only rank up by beating its own rank or higher."); }

        // does not have this rule.
        inline const char* does_not_have_this_rule() const { return Get("does not have this rule."); }

        // promotion counter
        inline const char* promotion_counter_2() const { return Get("promotion counter"); }

        // demotion counter
        inline const char* demotion_counter_2() const { return Get("demotion counter"); }

        // is enabled at %d points
        inline const char* is_enabled_at_d_points() const { return Get("is enabled at %d points"); }

        // is enabled at %d strikes
        inline const char* is_enabled_at_d_strikes() const { return Get("is enabled at %d strikes"); }

        // is disabled
        inline const char* is_disabled() const { return Get("is disabled"); }

        // promotion counter gain applies against
        inline const char* promotion_counter_gain_applies_against() const { return Get("promotion counter gain applies against"); }

        // adds demotion strikes when losing to
        inline const char* adds_demotion_strikes_when_losing_to() const { return Get("adds demotion strikes when losing to"); }

        // resets demotion strikes by winning against
        inline const char* resets_demotion_strikes_by_winning_against() const { return Get("resets demotion strikes by winning against"); }

        // resets promotion points by losing to
        inline const char* resets_promotion_points_by_losing_to() const { return Get("resets promotion points by losing to"); }

        // No rule differences were detected for these ranks.
        inline const char* No_rule_differences_were_detected_for_these_ranks() const { return Get("No rule differences were detected for these ranks."); }

        // YOU ARE NOT IN A ROOM OR ONLINE MATCH!
        inline const char* YOU_ARE_NOT_IN_A_ROOM_OR_ONLINE_MATCH() const { return Get("YOU ARE NOT IN A ROOM OR ONLINE MATCH!"); }

        // Online type: %s
        inline const char* Online_type_s() const { return Get("Online type: %s"); }

        // Improvement Mod users in Room:
        inline const char* Improvement_Mod_users_in_Room() const { return Get("Improvement Mod users in Room:"); }

        // Improvement Mod users in match:
        inline const char* Improvement_Mod_users_in_match() const { return Get("Improvement Mod users in match:"); }

        // Click to open Steam profile
        inline const char* Click_to_open_Steam_profile() const { return Get("Click to open Steam profile"); }

        // Spectator
        inline const char* Spectator() const { return Get("Spectator"); }

        // Online room window title format
        inline const char* Online_room_window_title_format() const { return Get("Online room window title format"); }

        // Wine or Proton detected
        inline const char* Wine_or_Proton_detected() const { return Get("Wine or Proton detected"); }

        // Wine/Proton detected. Controller hooks were disabled to prevent startup crashes. Enable below or set ForceEnableControllerSettingHooks to 1 in settings.ini to override detection.
        inline const char* Wine_Proton_detected_Controller_hooks_were_disabled_to_prevent_startup_crashes_Enable_below_or_set_ForceEnableControllerSettingHooks_to_1_in_settings_ini_to_override_detection() const { return Get("Wine/Proton detected. Controller hooks were disabled to prevent startup crashes. Enable below or set ForceEnableControllerSettingHooks to 1 in settings.ini to override detection."); }

        // Enable anyway
        inline const char* Enable_anyway() const { return Get("Enable anyway"); }

        // Keep disabled
        inline const char* Keep_disabled() const { return Get("Keep disabled"); }

        // Controller hooks are disabled because EnableControllerHooks is set to 0.
        inline const char* Controller_hooks_are_disabled_because_EnableControllerHooks_is_set_to_0() const { return Get("Controller hooks are disabled because EnableControllerHooks is set to 0."); }

        // This might have been set manually or after detecting Wine/Proton.
        inline const char* This_might_have_been_set_manually_or_after_detecting_Wine_Proton() const { return Get("This might have been set manually or after detecting Wine/Proton."); }

        // To force enable these hooks, set ForceEnableControllerSettingHooks to 1 at your own risk.
        inline const char* To_force_enable_these_hooks_set_ForceEnableControllerSettingHooks_to_1_at_your_own_risk() const { return Get("To force enable these hooks, set ForceEnableControllerSettingHooks to 1 at your own risk."); }

        // Unlimited Playback (BETA)
        inline const char* Unlimited_Playback_BETA() const { return Get("Unlimited Playback (BETA)"); }

        // Popup is always available. Runtime actions only work in the right context.
        inline const char* Popup_is_always_available_Runtime_actions_only_work_in_the_right_context() const { return Get("Popup is always available. Runtime actions only work in the right context."); }

        // Loop current playback
        inline const char* Loop_current_playback() const { return Get("Loop current playback"); }

        // This will continuously loop the current recording slot
        inline const char* This_will_continuously_loop_the_current_recording_slot() const { return Get("This will continuously loop the current recording slot"); }

        // A native file dialog is already open.
        inline const char* A_native_file_dialog_is_already_open() const { return Get("A native file dialog is already open."); }

        // Mapped playback bind: %s
        inline const char* Mapped_playback_bind_s() const { return Get("Mapped playback bind: %s"); }

        // Profile Compatibility
        inline const char* Profile_Compatibility() const { return Get("Profile Compatibility"); }

        // Profile version mismatch.\n\nFile version: %s\nCode version: %s\n\n%s
        inline const char* Profile_version_mismatch_File_version_s_Code_version_s_s() const { return Get("Profile version mismatch.\n\nFile version: %s\nCode version: %s\n\n%s"); }

        // Load Anyway
        inline const char* Load_Anyway() const { return Get("Load Anyway"); }

        // Playback Compatibility
        inline const char* Playback_Compatibility() const { return Get("Playback Compatibility"); }

        // Playback version mismatch.\n\nFile version: %s\nCode version: %s\n\n%s
        inline const char* Playback_version_mismatch_File_version_s_Code_version_s_s() const { return Get("Playback version mismatch.\n\nFile version: %s\nCode version: %s\n\n%s"); }

        // Import Anyway
        inline const char* Import_Anyway() const { return Get("Import Anyway"); }

        // Add from CF Slot
        inline const char* Add_from_CF_Slot() const { return Get("Add from CF Slot"); }

        // Add from file
        inline const char* Add_from_file() const { return Get("Add from file"); }

        // Add from replay
        inline const char* Add_from_replay() const { return Get("Add from replay"); }

        // Capture a playback from one of the 4 CF slots
        inline const char* Capture_a_playback_from_one_of_the_4_CF_slots() const { return Get("Capture a playback from one of the 4 CF slots"); }

        // Import a playback file into the library
        inline const char* Import_a_playback_file_into_the_library() const { return Get("Import a playback file into the library"); }

        // Record a new playback entry from a replay
        inline const char* Record_a_new_playback_entry_from_a_replay() const { return Get("Record a new playback entry from a replay"); }

        // Library (%d)
        inline const char* Library_d() const { return Get("Library (%d)"); }

        // Send to CF Slot
        inline const char* Send_to_CF_Slot() const { return Get("Send to CF Slot"); }

        // Save to File
        inline const char* Save_to_File() const { return Get("Save to File"); }

        // Export playback entry file dialog open...
        inline const char* Export_playback_entry_file_dialog_open() const { return Get("Export playback entry file dialog open..."); }

        // Play
        inline const char* Play() const { return Get("Play"); }

        // Play (Disabled due to not being in lab)
        inline const char* Play_Disabled_due_to_not_being_in_lab() const { return Get("Play (Disabled due to not being in lab)"); }

        // Edit
        inline const char* Edit() const { return Get("Edit"); }

        // Delete
        inline const char* Delete() const { return Get("Delete"); }

        // Default
        inline const char* Default() const { return Get("Default"); }

        // Load a library profile
        inline const char* Load_a_library_profile() const { return Get("Load a library profile"); }

        // Save the current library as a profile
        inline const char* Save_the_current_library_as_a_profile() const { return Get("Save the current library as a profile"); }

        // Reset the current library
        inline const char* Reset_the_current_library() const { return Get("Reset the current library"); }

        // Load profile file dialog open...
        inline const char* Load_profile_file_dialog_open() const { return Get("Load profile file dialog open..."); }

        // Save profile file dialog open...
        inline const char* Save_profile_file_dialog_open() const { return Get("Save profile file dialog open..."); }

        // Add Playback Entry
        inline const char* Add_Playback_Entry() const { return Get("Add Playback Entry"); }

        // Add from replay is only available while a replay match is active in Replay Theater.
        inline const char* Add_from_replay_is_only_available_while_a_replay_match_is_active_in_Replay_Theater() const { return Get("Add from replay is only available while a replay match is active in Replay Theater."); }

        // Import playback file dialog open...
        inline const char* Import_playback_file_dialog_open() const { return Get("Import playback file dialog open..."); }

        // Add from Replay
        inline const char* Add_from_Replay_2() const { return Get("Add from Replay"); }

        // Capture from replay
        inline const char* Capture_from_replay() const { return Get("Capture from replay"); }

        // Recording %s inputs (start frame %d)
        inline const char* Recording_s_inputs_start_frame_d() const { return Get("Recording %s inputs (start frame %d)"); }

        // Name
        inline const char* Name() const { return Get("Name"); }

        // Stop and Save
        inline const char* Stop_and_Save() const { return Get("Stop and Save"); }

        // Record P1 Inputs
        inline const char* Record_P1_Inputs() const { return Get("Record P1 Inputs"); }

        // Record P2 Inputs
        inline const char* Record_P2_Inputs() const { return Get("Record P2 Inputs"); }

        // Replay capture only starts while a replay match is active.
        inline const char* Replay_capture_only_starts_while_a_replay_match_is_active() const { return Get("Replay capture only starts while a replay match is active."); }

        // Library Settings
        inline const char* Library_Settings() const { return Get("Library Settings"); }

        // Random
        inline const char* Random() const { return Get("Random"); }

        // Sequential
        inline const char* Sequential() const { return Get("Sequential"); }

        // Non-repeating Random
        inline const char* Non_repeating_Random() const { return Get("Non-repeating Random"); }

        // Playback Mode
        inline const char* Playback_Mode() const { return Get("Playback Mode"); }

        // How the library chooses the next enabled entry when playback is triggered.
        inline const char* How_the_library_chooses_the_next_enabled_entry_when_playback_is_triggered() const { return Get("How the library chooses the next enabled entry when playback is triggered."); }

        // Playback mode: %s
        inline const char* Playback_mode_s() const { return Get("Playback mode: %s"); }

        // Auto-mirror on side swap
        inline const char* Auto_mirror_on_side_swap() const { return Get("Auto-mirror on side swap"); }

        // Mirrors directional inputs when the recorded side and current side differ.
        inline const char* Mirrors_directional_inputs_when_the_recorded_side_and_current_side_differ() const { return Get("Mirrors directional inputs when the recorded side and current side differ."); }

        // Wakeup
        inline const char* Wakeup() const { return Get("Wakeup"); }

        // On Block
        inline const char* On_Block() const { return Get("On Block"); }

        // On Hit
        inline const char* On_Hit() const { return Get("On Hit"); }

        // Throw Tech
        inline const char* Throw_Tech() const { return Get("Throw Tech"); }

        // Key Press
        inline const char* Key_Press() const { return Get("Key Press"); }

        // Unknown
        inline const char* Unknown_2() const { return Get("Unknown"); }

        // Playback Trigger Type
        inline const char* Playback_Trigger_Type() const { return Get("Playback Trigger Type"); }

        // Selects the single trigger type that can fire library playback.
        inline const char* Selects_the_single_trigger_type_that_can_fire_library_playback() const { return Get("Selects the single trigger type that can fire library playback."); }

        // Playback trigger: %s
        inline const char* Playback_trigger_s() const { return Get("Playback trigger: %s"); }

        // %s Config
        inline const char* s_Config() const { return Get("%s Config"); }

        // Cooldown Frames
        inline const char* Cooldown_Frames() const { return Get("Cooldown Frames"); }

        // Blocks the same trigger from firing again for this many frames after it activates.
        inline const char* Blocks_the_same_trigger_from_firing_again_for_this_many_frames_after_it_activates() const { return Get("Blocks the same trigger from firing again for this many frames after it activates."); }

        // Maps the button or key used by the Key Press trigger.
        inline const char* Maps_the_button_or_key_used_by_the_Key_Press_trigger() const { return Get("Maps the button or key used by the Key Press trigger."); }

        // Map Playback Bind
        inline const char* Map_Playback_Bind() const { return Get("Map Playback Bind"); }

        // Fix Triggers
        inline const char* Fix_Triggers() const { return Get("Fix Triggers"); }

        // Use this after Training reset if triggers temporarily stop firing. It clears trigger cooldown and edge state.
        inline const char* Use_this_after_Training_reset_if_triggers_temporarily_stop_firing_It_clears_trigger_cooldown_and_edge_state() const { return Get("Use this after Training reset if triggers temporarily stop firing. It clears trigger cooldown and edge state."); }

        // Activity
        inline const char* Activity() const { return Get("Activity"); }

        // Reset Library?
        inline const char* Reset_Library() const { return Get("Reset Library?"); }

        // Reset the current library and clear all loaded entries?
        inline const char* Reset_the_current_library_and_clear_all_loaded_entries() const { return Get("Reset the current library and clear all loaded entries?"); }

        // Reset
        inline const char* Reset_2() const { return Get("Reset"); }

        // Delete Entry?
        inline const char* Delete_Entry() const { return Get("Delete Entry?"); }

        // Delete this playback entry from the library?
        inline const char* Delete_this_playback_entry_from_the_library() const { return Get("Delete this playback entry from the library?"); }

        // Capture Slot
        inline const char* Capture_Slot() const { return Get("Capture Slot"); }

        // Edit Library Entry
        inline const char* Edit_Library_Entry() const { return Get("Edit Library Entry"); }

        // Weight
        inline const char* Weight() const { return Get("Weight"); }

        // Edit Playback
        inline const char* Edit_Playback() const { return Get("Edit Playback"); }

        // Entry updated.
        inline const char* Entry_updated() const { return Get("Entry updated."); }

        // Edit Entry Playback
        inline const char* Edit_Entry_Playback() const { return Get("Edit Entry Playback"); }

        // Playback editor is unavailable.
        inline const char* Playback_editor_is_unavailable() const { return Get("Playback editor is unavailable."); }

        // Entry no longer exists.
        inline const char* Entry_no_longer_exists() const { return Get("Entry no longer exists."); }

        // CF Slot
        inline const char* CF_Slot() const { return Get("CF Slot"); }

        // Send
        inline const char* Send() const { return Get("Send"); }

        // Load unlimited playback profile
        inline const char* Load_unlimited_playback_profile() const { return Get("Load unlimited playback profile"); }

        // Save unlimited playback profile
        inline const char* Save_unlimited_playback_profile() const { return Get("Save unlimited playback profile"); }

        // Import unlimited playback entry
        inline const char* Import_unlimited_playback_entry() const { return Get("Import unlimited playback entry"); }

        // Export unlimited playback entry
        inline const char* Export_unlimited_playback_entry() const { return Get("Export unlimited playback entry"); }

        // Pad A
        inline const char* Pad_A() const { return Get("Pad A"); }

        // Pad B
        inline const char* Pad_B() const { return Get("Pad B"); }

        // Pad X
        inline const char* Pad_X() const { return Get("Pad X"); }

        // Pad Y
        inline const char* Pad_Y() const { return Get("Pad Y"); }

        // Pad LB
        inline const char* Pad_LB() const { return Get("Pad LB"); }

        // Pad RB
        inline const char* Pad_RB() const { return Get("Pad RB"); }

        // Pad Back
        inline const char* Pad_Back() const { return Get("Pad Back"); }

        // Pad Start
        inline const char* Pad_Start() const { return Get("Pad Start"); }

        // Pad LS
        inline const char* Pad_LS() const { return Get("Pad LS"); }

        // Pad RS
        inline const char* Pad_RS() const { return Get("Pad RS"); }

        // Pad Up
        inline const char* Pad_Up() const { return Get("Pad Up"); }

        // Pad Down
        inline const char* Pad_Down() const { return Get("Pad Down"); }

        // Pad Left
        inline const char* Pad_Left() const { return Get("Pad Left"); }

        // Pad Right
        inline const char* Pad_Right() const { return Get("Pad Right"); }

        // VK_%d
        inline const char* VK_d() const { return Get("VK_%d"); }

        // Invalid playback destination.
        inline const char* Invalid_playback_destination() const { return Get("Invalid playback destination."); }

        // Playback payload was too small.
        inline const char* Playback_payload_was_too_small() const { return Get("Playback payload was too small."); }

        // Playback rejected: file v%s, code v%s.
        inline const char* Playback_rejected_file_v_s_code_v_s() const { return Get("Playback rejected: file v%s, code v%s."); }

        // Playback file header is missing.
        inline const char* Playback_file_header_is_missing() const { return Get("Playback file header is missing."); }

        // Trigger runtime state reset.
        inline const char* Trigger_runtime_state_reset() const { return Get("Trigger runtime state reset."); }

        // Trigger runtime resynced after training reset.
        inline const char* Trigger_runtime_resynced_after_training_reset() const { return Get("Trigger runtime resynced after training reset."); }

        // Could not read playback file.
        inline const char* Could_not_read_playback_file() const { return Get("Could not read playback file."); }

        // File not found.
        inline const char* File_not_found() const { return Get("File not found."); }

        // Invalid playback file.
        inline const char* Invalid_playback_file() const { return Get("Invalid playback file."); }

        // Playback imported.
        inline const char* Playback_imported() const { return Get("Playback imported."); }

        // Slot must be between 1 and 4.
        inline const char* Slot_must_be_between_1_and_4() const { return Get("Slot must be between 1 and 4."); }

        // Captured slot to library.
        inline const char* Captured_slot_to_library() const { return Get("Captured slot to library."); }

        // Start replay recording only while a replay match is active.
        inline const char* Start_replay_recording_only_while_a_replay_match_is_active() const { return Get("Start replay recording only while a replay match is active."); }

        // Replay recording started: %s.
        inline const char* Replay_recording_started_s() const { return Get("Replay recording started: %s."); }

        // No replay recording in progress.
        inline const char* No_replay_recording_in_progress() const { return Get("No replay recording in progress."); }

        // Replay recording cancelled (left replay match).
        inline const char* Replay_recording_cancelled_left_replay_match() const { return Get("Replay recording cancelled (left replay match)."); }

        // Replay recording cancelled (too short).
        inline const char* Replay_recording_cancelled_too_short() const { return Get("Replay recording cancelled (too short)."); }

        // Replay recording cancelled (failed reading replay frames).
        inline const char* Replay_recording_cancelled_failed_reading_replay_frames() const { return Get("Replay recording cancelled (failed reading replay frames)."); }

        // Replay recording saved to library.
        inline const char* Replay_recording_saved_to_library() const { return Get("Replay recording saved to library."); }

        // Entry removed.
        inline const char* Entry_removed() const { return Get("Entry removed."); }

        // Entry renamed.
        inline const char* Entry_renamed() const { return Get("Entry renamed."); }

        // Sending to a CF slot works only during a training match.
        inline const char* Sending_to_a_CF_slot_works_only_during_a_training_match() const { return Get("Sending to a CF slot works only during a training match."); }

        // Failed loading entry.
        inline const char* Failed_loading_entry() const { return Get("Failed loading entry."); }

        // Entry loaded into slot.
        inline const char* Entry_loaded_into_slot() const { return Get("Entry loaded into slot."); }

        // Entry overwritten from slot.
        inline const char* Entry_overwritten_from_slot() const { return Get("Entry overwritten from slot."); }

        // Entry saved.
        inline const char* Entry_saved() const { return Get("Entry saved."); }

        // Failed saving entry to file.
        inline const char* Failed_saving_entry_to_file() const { return Get("Failed saving entry to file."); }

        // Entry saved to file.
        inline const char* Entry_saved_to_file() const { return Get("Entry saved to file."); }

        // Play now works only during a training match.
        inline const char* Play_now_works_only_during_a_training_match() const { return Get("Play now works only during a training match."); }

        // Played: %s%s
        inline const char* Played_s_s() const { return Get("Played: %s%s"); }

        // (mirrored)
        inline const char* mirrored() const { return Get("(mirrored)"); }

        // Unlimited playback config cleared.
        inline const char* Unlimited_playback_config_cleared() const { return Get("Unlimited playback config cleared."); }

        // Failed to save profile.
        inline const char* Failed_to_save_profile() const { return Get("Failed to save profile."); }

        // Profile save failed: entry data missing for '%s'.
        inline const char* Profile_save_failed_entry_data_missing_for_s() const { return Get("Profile save failed: entry data missing for '%s'."); }

        // Profile saved.
        inline const char* Profile_saved() const { return Get("Profile saved."); }

        // Could not read profile file.
        inline const char* Could_not_read_profile_file() const { return Get("Could not read profile file."); }

        // Failed to open profile.
        inline const char* Failed_to_open_profile() const { return Get("Failed to open profile."); }

        // Playback rejected (newer format): file v%s, code v%s.
        inline const char* Playback_rejected_newer_format_file_v_s_code_v_s() const { return Get("Playback rejected (newer format): file v%s, code v%s."); }

        // Profile compatibility rejected (file v%s, code v%s).
        inline const char* Profile_compatibility_rejected_file_v_s_code_v_s() const { return Get("Profile compatibility rejected (file v%s, code v%s)."); }

        // Profile version mismatch requires confirmation (file v%s, code v%s).
        inline const char* Profile_version_mismatch_requires_confirmation_file_v_s_code_v_s() const { return Get("Profile version mismatch requires confirmation (file v%s, code v%s)."); }

        // Profile load failed: embedded playback missing for '%s'.
        inline const char* Profile_load_failed_embedded_playback_missing_for_s() const { return Get("Profile load failed: embedded playback missing for '%s'."); }

        // Profile load failed for '%s': %s
        inline const char* Profile_load_failed_for_s_s() const { return Get("Profile load failed for '%s': %s"); }

        // Profile load failed for '%s'.
        inline const char* Profile_load_failed_for_s() const { return Get("Profile load failed for '%s'."); }

        // Profile loaded. Trigger runtime synced.
        inline const char* Profile_loaded_Trigger_runtime_synced() const { return Get("Profile loaded. Trigger runtime synced."); }

        // Trigger detected: %s
        inline const char* Trigger_detected_s() const { return Get("Trigger detected: %s"); }

        // No eligible playback in current trigger selection.
        inline const char* No_eligible_playback_in_current_trigger_selection() const { return Get("No eligible playback in current trigger selection."); }

        // Selected playback cache missing.
        inline const char* Selected_playback_cache_missing() const { return Get("Selected playback cache missing."); }

        // Triggered [%s]: %s%s
        inline const char* Triggered_s_s_s() const { return Get("Triggered [%s]: %s%s"); }

        // Slot %d
        inline const char* Slot_d() const { return Get("Slot %d"); }

        // Replay %s
        inline const char* Replay_s() const { return Get("Replay %s"); }

        // Slot moved.
        inline const char* Slot_moved() const { return Get("Slot moved."); }

        // All slots enabled.
        inline const char* All_slots_enabled() const { return Get("All slots enabled."); }

        // All slots disabled.
        inline const char* All_slots_disabled() const { return Get("All slots disabled."); }

        // Dragged slot: %s
        inline const char* Dragged_slot_s() const { return Get("Dragged slot: %s"); }

        // Current Slot - %s
        inline const char* Current_Slot_s() const { return Get("Current Slot - %s"); }

        // Slot list
        inline const char* Slot_list() const { return Get("Slot list"); }

        // Move up
        inline const char* Move_up() const { return Get("Move up"); }

        // Move down
        inline const char* Move_down() const { return Get("Move down"); }

        // Set index...
        inline const char* Set_index() const { return Get("Set index..."); }

        // Set Slot Index
        inline const char* Set_Slot_Index() const { return Get("Set Slot Index"); }

        // Index
        inline const char* Index() const { return Get("Index"); }

        // Valid range: 1-%d
        inline const char* Valid_range_1_d() const { return Get("Valid range: 1-%d"); }

        // Move
        inline const char* Move() const { return Get("Move"); }

        // Turn ALL slots off
        inline const char* Turn_ALL_slots_off() const { return Get("Turn ALL slots off"); }

        // Turn ALL slots on
        inline const char* Turn_ALL_slots_on() const { return Get("Turn ALL slots on"); }

        // Network Square Color
        inline const char* Network_Square_Color() const { return Get("Network Square Color"); }

        // White
        inline const char* White() const { return Get("White"); }

        // Purple
        inline const char* Purple() const { return Get("Purple"); }

        // Red
        inline const char* Red() const { return Get("Red"); }

        // Orange
        inline const char* Orange() const { return Get("Orange"); }

        // Yellow
        inline const char* Yellow() const { return Get("Yellow"); }

        // Green
        inline const char* Green() const { return Get("Green"); }

        // Blue
        inline const char* Blue() const { return Get("Blue"); }

        // Teal
        inline const char* Teal() const { return Get("Teal"); }

        // Black
        inline const char* Black() const { return Get("Black"); }

        // Unknown (%u)
        inline const char* Unknown_u() const { return Get("Unknown (%u)"); }

        // Invalid (%u)
        inline const char* Invalid_u() const { return Get("Invalid (%u)"); }

        // Unavailable
        inline const char* Unavailable() const { return Get("Unavailable"); }

        // Offline or unavailable
        inline const char* Offline_or_unavailable() const { return Get("Offline or unavailable"); }

        // Local color
        inline const char* Local_color() const { return Get("Local color"); }

        // Counter
        inline const char* Counter() const { return Get("Counter"); }

        // Next color
        inline const char* Next_color() const { return Get("Next color"); }

        // Previous color
        inline const char* Previous_color() const { return Get("Previous color"); }

        // Distance to rank up
        inline const char* Distance_to_rank_up() const { return Get("Distance to rank up"); }

        // Distance to rank down
        inline const char* Distance_to_rank_down() const { return Get("Distance to rank down"); }

        // Opponent color
        inline const char* Opponent_color() const { return Get("Opponent color"); }

        // Top color
        inline const char* Top_color() const { return Get("Top color"); }

        // Bottom color
        inline const char* Bottom_color() const { return Get("Bottom color"); }

        // Color changes at %u / %u and counter resets to %u after a color change.
        inline const char* Color_changes_at_u_u_and_counter_resets_to_u_after_a_color_change() const { return Get("Color changes at %u / %u and counter resets to %u after a color change."); }

        // Wins increase the counter; losses decrease it. Same-color matches are the ones that move square color.
        inline const char* Wins_increase_the_counter_losses_decrease_it_Same_color_matches_are_the_ones_that_move_square_color() const { return Get("Wins increase the counter; losses decrease it. Same-color matches are the ones that move square color."); }

        // Update available
        inline const char* Update_available() const { return Get("Update available"); }

        // BBCF Improvement Mod %s is available
        inline const char* BBCF_Improvement_Mod_s_is_available() const { return Get("BBCF Improvement Mod %s is available"); }

        // Development update channel
        inline const char* Development_update_channel() const { return Get("Development update channel"); }

        // Release notes
        inline const char* Release_notes() const { return Get("Release notes"); }

        // Update
        inline const char* Update() const { return Get("Update"); }

        // Later
        inline const char* Later() const { return Get("Later"); }

        // Skip this version
        inline const char* Skip_this_version() const { return Get("Skip this version"); }

        // Open release page
        inline const char* Open_release_page() const { return Get("Open release page"); }

        // Update to %s
        inline const char* Update_to_s() const { return Get("Update to %s"); }
};


